name: 'Test Report'
on:
  workflow_run:
    workflows: ['Java CI with Maven']                     # runs after CI workflow
    types:
      - completed
permissions:
  contents: read
  actions: read
  checks: write
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
    - uses: dorny/test-reporter@v1
      with:
        artifact: Service-Unit-Test-Results            # artifact name
        name: Service-Unit-Test-Results
        path: 'surefire-reports/*.xml'                     # Path to test results (inside artifact .zip)
        reporter: java-junit              # Format of test results
